# Generated by Django 5.1.1 on 2024-11-12 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0002_billing_equipment_member_membership_plan_planbilling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homeApp.member')),
            ],
        ),
    ]
