# Generated by Django 5.1.1 on 2024-11-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0004_alter_plan_duration_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration_months',
            field=models.IntegerField(default=2),
        ),
    ]
