# Generated by Django 5.1.1 on 2024-11-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0007_rename_trainerspecialty_trainerspeciality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='speciality',
            field=models.CharField(default='not assigned', max_length=30),
        ),
    ]
