# Generated by Django 5.1.1 on 2024-11-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0008_trainer_speciality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainerspeciality',
            old_name='speciality',
            new_name='specialty',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='speciality',
            field=models.CharField(max_length=30),
        ),
    ]
