# Generated by Django 5.1.1 on 2024-11-23 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0009_rename_speciality_trainerspeciality_specialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homeApp.member'),
        ),
    ]
