# Generated by Django 5.1.3 on 2024-11-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0011_billing_additional_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
